### ISSUE TITLE
Poetry 1.8 and Python 3.9?

### ISSUE THREAD

**Issue by MattGurney** [mwalbeck/docker-python-poetry#1]
Firstly, thanks for maintaining this repo. 

Not sure if this is the place to ask, but I just wanted to let you know that we could use a Poetry 1.8 with Python 3.9 repo. We would like to be current with Poetry, but are locked into Python 3.9 for a while. We can work around by using your mwalbeck/python-poetry:1.7.1-3.9 and upgrading Poetry to 1.8.

As you can see, there a lot of changes with Poetry 1.8: https://python-poetry.org/blog/announcing-poetry-1.8.0/

**Comment by mwalbeck** [comment]
Sure thing! The images should be updated to Poetry 1.8.2 shortly.

Cheers!

**Comment by mwalbeck** [comment]
My build system is acting up a bit, so whenever it's back to normal the images should be out, hopefully some time tomorrow
